### ISSUE TITLE
想问下模型在同域测试集上指标多少啊

### ISSUE THREAD

**Issue by ycy-upup** [FlyingRoastDuck/ACT_AAAI20#1]

**Comment by FlyingRoastDuck** [comment]
source model在同domain的指标为：
DukeMTMC：mAP=69.7, rank-1=83.0
Market1501: mAP=79.1, rank-1=91.2

相关source model已经上传至：[百度云盘](https://pan.baidu.com/s/12791TcLiJ_PIOcDIxdeSXg)
我们在source model基础上先用了DBSCAN微调一波，再在微调模型上使用ACT。

**Comment by FlyingRoastDuck** [comment]
Since no further problem is proposed, I will close this issue.
