### ISSUE TITLE
Cannot obtain the reported performance by directly running the selftrainingACT.py

### ISSUE THREAD

**Issue by zlin-code** [FlyingRoastDuck/ACT_AAAI20#2]
Hi, I would like to thank you for releasing the codes in the first place.

Following the readme.md, we directly run the  selftrainingACT.py without any modification, but fail to obtain the reported performance，Can you help us figure out what the problem is?
To be more specific, we obtain Mean AP:  48.3% and top1: 67.1 %  after training for 30 epoches by running the command
python selftrainingACT.py  --src_dataset market1501  --tgt_dataset dukemtmc --resume ./ACT_pretrain/logMar/adaM2D.pth  --data_dir ./data --logs_dir ./logs

**Comment by FlyingRoastDuck** [comment]
Hi, I checked my logs and find that mAP scores will quickly rise to 50+ after 3 epochs. Could you please provide more information about the implementation details? By the way, please send email to me directly. I can not reply GitHub issues in time.
![image](https://user-images.githubusercontent.com/29745430/90723212-e9279280-e2ee-11ea-8a4e-b5d1a08dd3eb.png)

**Comment by FlyingRoastDuck** [comment]
No response. I will close this issue.
