### ISSUE TITLE
msmt17

### ISSUE THREAD

**Issue by RitaDel** [FlyingRoastDuck/ACT_AAAI20#4]
I would like to reproduce your results on msmt17 (both as the source and the target domain). Pre-trained models are not available. Can you share them?

Thank you

**Comment by FlyingRoastDuck** [comment]
Hi, I'm currently engaged in the rebuttal of CVPR and do not have much time to run the model for you. It is easy to obtain such pre-trained models by utilizing selftraining.py of [DomainAdaptive-ReID](https://github.com/LcDog/DomainAdaptiveReID). Don't forget to cite them when you use their code for your project~.

**Comment by RitaDel** [comment]
I tried to use their code. Maybe, there are some problems with my conda environment. I'll ask the authors about the requirements to run the code.
Thanks.
